{
    "fields": [
        {
            "system_mandatory": false,
            "webhook": true,
            "json_type": "string",
            "crypt": null,
            "field_label": "Quote. No.",
            "tooltip": null,
            "created_source": "default",
            "field_read_only": false,
            "display_label": "Quote. No.",
            "ui_type": 111,
            "read_only": false,
            "association_details": null,
            "businesscard_supported": true,
            "currency": {},
            "id": "5653678000001141102",
            "custom_field": true,
            "lookup": {},
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 255,
            "view_type": {
                "view": true,
                "edit": false,
                "quick_create": false,
                "create": false
            },
            "subform": null,
            "external": null,
            "api_name": "Quote_No",
            "unique": {},
            "history_tracking": false,
            "data_type": "autonumber",
            "formula": {},
            "decimal_place": null,
            "mass_update": false,
            "multiselectlookup": {},
            "pick_list_values": [],
            "auto_number": {
                "starting_number_length": 4,
                "prefix": "VTNX-",
                "start_number": 2500,
                "suffix": ""
            }
        },
        {
            "system_mandatory": false,
            "webhook": true,
            "json_type": "string",
            "crypt": null,
            "field_label": "Quote Number",
            "tooltip": null,
            "created_source": "default",
            "field_read_only": true,
            "display_label": "Quote Number",
            "ui_type": 52,
            "read_only": true,
            "association_details": null,
            "businesscard_supported": true,
            "currency": {},
            "id": "5653678000000002867",
            "custom_field": false,
            "lookup": {},
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 120,
            "view_type": {
                "view": true,
                "edit": false,
                "quick_create": false,
                "create": true
            },
            "subform": null,
            "external": null,
            "api_name": "Quote_Number",
            "unique": {},
            "history_tracking": false,
            "data_type": "autonumber",
            "formula": {},
            "decimal_place": null,
            "mass_update": false,
            "multiselectlookup": {},
            "pick_list_values": [],
            "auto_number": {
                "prefix": null,
                "start_number": null,
                "suffix": null
            }
        },
        {
            "system_mandatory": false,
            "webhook": true,
            "json_type": "jsonobject",
            "crypt": null,
            "field_label": "Quote Owner",
            "tooltip": null,
            "created_source": "default",
            "field_read_only": true,
            "display_label": "Quote Owner",
            "ui_type": 8,
            "read_only": false,
            "association_details": null,
            "businesscard_supported": true,
            "currency": {},
            "id": "5653678000000002885",
            "custom_field": false,
            "lookup": {},
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 120,
            "view_type": {
                "view": true,
                "edit": true,
                "quick_create": false,
                "create": true
            },
            "subform": null,
            "external": null,
            "api_name": "Owner",
            "unique": {},
            "history_tracking": false,
            "data_type": "ownerlookup",
            "formula": {},
            "decimal_place": null,
            "mass_update": false,
            "multiselectlookup": {},
            "pick_list_values": [],
            "auto_number": {}
        },
        {
            "system_mandatory": false,
            "webhook": true,
            "json_type": "jsonobject",
            "crypt": null,
            "field_label": "Deal Name",
            "tooltip": null,
            "created_source": "default",
            "field_read_only": false,
            "display_label": "Potential Name",
            "ui_type": 133,
            "read_only": false,
            "association_details": null,
            "businesscard_supported": true,
            "currency": {},
            "id": "5653678000000002871",
            "custom_field": false,
            "lookup": {
                "display_label": "Quotes",
                "api_name": "Quotes",
                "module": "Deals",
                "id": "5653678000000003829"
            },
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 120,
            "view_type": {
                "view": true,
                "edit": true,
                "quick_create": false,
                "create": true
            },
            "subform": null,
            "external": null,
            "api_name": "Deal_Name",
            "unique": {},
            "history_tracking": false,
            "data_type": "lookup",
            "formula": {},
            "decimal_place": null,
            "mass_update": false,
            "multiselectlookup": {},
            "pick_list_values": [],
            "auto_number": {}
        },
        {
            "system_mandatory": false,
            "webhook": true,
            "json_type": "string",
            "crypt": null,
            "field_label": "Assign Department",
            "tooltip": null,
            "created_source": "default",
            "field_read_only": false,
            "display_label": "Assign Department",
            "ui_type": 2,
            "read_only": false,
            "association_details": null,
            "businesscard_supported": true,
            "currency": {},
            "id": "5653678000000801455",
            "custom_field": true,
            "lookup": {},
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 120,
            "view_type": {
                "view": true,
                "edit": true,
                "quick_create": false,
                "create": true
            },
            "subform": null,
            "external": null,
            "api_name": "Assign_Department",
            "unique": {},
            "history_tracking": true,
            "data_type": "picklist",
            "formula": {},
            "decimal_place": null,
            "mass_update": true,
            "blueprint_supported": true,
            "multiselectlookup": {},
            "pick_list_values": [
                {
                    "display_value": "-None-",
                    "reference_value": "-None-",
                    "actual_value": "-None-"
                },
                {
                    "display_value": "VOLTRONIX CONTRACTING LLC",
                    "reference_value": "VOLTRONIX CONTRACTING LLC",
                    "actual_value": "VOLTRONIX CONTRACTING LLC"
                },
                {
                    "display_value": "VOLTRONIX SWICHGEAR LLC",
                    "reference_value": "VOLTRONIX SWICHGEAR LLC",
                    "actual_value": "VOLTRONIX SWICHGEAR LLC"
                }
            ],
            "auto_number": {}
        },
        {
            "system_mandatory": false,
            "webhook": true,
            "json_type": "string",
            "crypt": null,
            "field_label": "Valid Until",
            "tooltip": null,
            "created_source": "default",
            "field_read_only": false,
            "display_label": "Valid Till",
            "ui_type": 24,
            "read_only": false,
            "association_details": null,
            "businesscard_supported": true,
            "currency": {},
            "id": "5653678000000002875",
            "custom_field": false,
            "lookup": {},
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 20,
            "view_type": {
                "view": true,
                "edit": true,
                "quick_create": false,
                "create": true
            },
            "subform": null,
            "external": null,
            "api_name": "Valid_Till",
            "unique": {},
            "history_tracking": false,
            "data_type": "date",
            "formula": {},
            "decimal_place": null,
            "mass_update": true,
            "multiselectlookup": {},
            "pick_list_values": [],
            "auto_number": {}
        },
        {
            "system_mandatory": false,
            "webhook": true,
            "json_type": "string",
            "crypt": null,
            "field_label": "Quote Type",
            "tooltip": null,
            "created_source": "default",
            "field_read_only": false,
            "display_label": "Quote Type",
            "ui_type": 2,
            "read_only": false,
            "association_details": null,
            "businesscard_supported": true,
            "currency": {},
            "id": "5653678000000810995",
            "custom_field": true,
            "lookup": {},
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 120,
            "view_type": {
                "view": true,
                "edit": true,
                "quick_create": false,
                "create": true
            },
            "subform": null,
            "external": null,
            "api_name": "Quote_Type",
            "unique": {},
            "history_tracking": false,
            "data_type": "picklist",
            "formula": {},
            "decimal_place": null,
            "mass_update": true,
            "blueprint_supported": true,
            "multiselectlookup": {},
            "pick_list_values": [
                {
                    "display_value": "-None-",
                    "reference_value": "-None-",
                    "actual_value": "-None-"
                },
                {
                    "display_value": "Switchgear",
                    "reference_value": "Switchgear",
                    "actual_value": "Switchgear"
                },
                {
                    "display_value": "Contracting Single",
                    "reference_value": "Contracting Single",
                    "actual_value": "Contracting Single"
                },
                {
                    "display_value": "Contracting Double",
                    "reference_value": "Contracting Double",
                    "actual_value": "Contracting Double"
                },
                {
                    "display_value": "Contracting 4 Page",
                    "reference_value": "Contracting 4 Page",
                    "actual_value": "Contracting 4 Page"
                }
            ],
            "auto_number": {}
        },
        {
            "system_mandatory": false,
            "webhook": true,
            "json_type": "jsonobject",
            "crypt": null,
            "field_label": "Contact Name",
            "tooltip": null,
            "created_source": "default",
            "field_read_only": false,
            "display_label": "Contact Name",
            "ui_type": 133,
            "read_only": false,
            "association_details": null,
            "businesscard_supported": true,
            "currency": {},
            "id": "5653678000000002879",
            "custom_field": false,
            "lookup": {
                "display_label": "Quotes",
                "api_name": "Quotes",
                "module": "Contacts",
                "id": "5653678000000003809"
            },
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 120,
            "view_type": {
                "view": true,
                "edit": true,
                "quick_create": false,
                "create": true
            },
            "subform": null,
            "external": null,
            "api_name": "Contact_Name",
            "unique": {},
            "history_tracking": false,
            "data_type": "lookup",
            "formula": {},
            "decimal_place": null,
            "mass_update": false,
            "multiselectlookup": {},
            "pick_list_values": [],
            "auto_number": {}
        },
        {
            "system_mandatory": true,
            "webhook": true,
            "json_type": "string",
            "crypt": null,
            "field_label": "Subject",
            "tooltip": null,
            "created_source": "default",
            "field_read_only": false,
            "display_label": "Subject",
            "ui_type": 1,
            "read_only": false,
            "association_details": null,
            "quick_sequence_number": "1",
            "businesscard_supported": false,
            "currency": {},
            "id": "5653678000000002869",
            "custom_field": false,
            "lookup": {},
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 120,
            "view_type": {
                "view": true,
                "edit": true,
                "quick_create": true,
                "create": true
            },
            "subform": null,
            "external": null,
            "api_name": "Subject",
            "unique": {},
            "history_tracking": false,
            "data_type": "text",
            "formula": {},
            "decimal_place": null,
            "mass_update": true,
            "multiselectlookup": {},
            "pick_list_values": [],
            "auto_number": {}
        },
        {
            "system_mandatory": false,
            "webhook": true,
            "json_type": "jsonobject",
            "crypt": null,
            "field_label": "Account Name",
            "tooltip": null,
            "created_source": "default",
            "field_read_only": false,
            "display_label": "Account Name",
            "ui_type": 133,
            "read_only": false,
            "association_details": null,
            "quick_sequence_number": "3",
            "businesscard_supported": true,
            "currency": {},
            "id": "5653678000000002883",
            "custom_field": false,
            "lookup": {
                "display_label": "Quotes",
                "api_name": "Quotes",
                "module": "Accounts",
                "id": "5653678000000003789"
            },
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 120,
            "view_type": {
                "view": true,
                "edit": true,
                "quick_create": true,
                "create": true
            },
            "subform": null,
            "external": null,
            "api_name": "Account_Name",
            "unique": {},
            "history_tracking": false,
            "data_type": "lookup",
            "formula": {},
            "decimal_place": null,
            "mass_update": false,
            "multiselectlookup": {},
            "pick_list_values": [],
            "auto_number": {}
        },
        {
            "system_mandatory": false,
            "webhook": true,
            "json_type": "string",
            "crypt": null,
            "field_label": "Project",
            "tooltip": null,
            "created_source": "default",
            "field_read_only": false,
            "display_label": "Project",
            "ui_type": 1,
            "read_only": false,
            "association_details": null,
            "businesscard_supported": true,
            "currency": {},
            "id": "5653678000000810914",
            "custom_field": true,
            "lookup": {},
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 255,
            "view_type": {
                "view": true,
                "edit": true,
                "quick_create": false,
                "create": true
            },
            "subform": null,
            "external": null,
            "api_name": "Project",
            "unique": {},
            "history_tracking": false,
            "data_type": "text",
            "formula": {},
            "decimal_place": null,
            "mass_update": true,
            "multiselectlookup": {},
            "pick_list_values": [],
            "auto_number": {}
        },
        {
            "system_mandatory": false,
            "webhook": true,
            "json_type": "jsonobject",
            "crypt": null,
            "field_label": "Modified By",
            "tooltip": null,
            "created_source": "default",
            "field_read_only": false,
            "display_label": "Modified By",
            "ui_type": 20,
            "read_only": false,
            "association_details": null,
            "businesscard_supported": true,
            "currency": {},
            "id": "5653678000000002889",
            "custom_field": false,
            "lookup": {},
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 120,
            "view_type": {
                "view": true,
                "edit": false,
                "quick_create": false,
                "create": false
            },
            "subform": null,
            "external": null,
            "api_name": "Modified_By",
            "unique": {},
            "history_tracking": false,
            "data_type": "ownerlookup",
            "formula": {},
            "decimal_place": null,
            "mass_update": false,
            "multiselectlookup": {},
            "pick_list_values": [],
            "auto_number": {}
        },
        {
            "system_mandatory": false,
            "webhook": true,
            "json_type": "string",
            "crypt": null,
            "field_label": "Terms of Payment",
            "tooltip": null,
            "created_source": "default",
            "field_read_only": false,
            "display_label": "Terms of Payment",
            "ui_type": 1,
            "read_only": false,
            "association_details": null,
            "businesscard_supported": true,
            "currency": {},
            "id": "5653678000000810934",
            "custom_field": true,
            "lookup": {},
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 255,
            "view_type": {
                "view": true,
                "edit": true,
                "quick_create": false,
                "create": true
            },
            "subform": null,
            "external": null,
            "api_name": "Terms_of_Payment",
            "unique": {},
            "history_tracking": false,
            "data_type": "text",
            "formula": {},
            "decimal_place": null,
            "mass_update": true,
            "multiselectlookup": {},
            "pick_list_values": [],
            "auto_number": {}
        },
        {
            "system_mandatory": false,
            "webhook": true,
            "json_type": "double",
            "crypt": null,
            "field_label": "Exchange Rate",
            "tooltip": null,
            "created_source": "default",
            "field_read_only": true,
            "display_label": "Exchange Rate",
            "ui_type": 40,
            "read_only": true,
            "association_details": null,
            "businesscard_supported": true,
            "currency": {},
            "id": "5653678000000050049",
            "custom_field": false,
            "lookup": {},
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 19,
            "view_type": {
                "view": true,
                "edit": true,
                "quick_create": false,
                "create": true
            },
            "subform": null,
            "external": null,
            "api_name": "Exchange_Rate",
            "unique": {},
            "history_tracking": false,
            "data_type": "double",
            "formula": {},
            "decimal_place": 9,
            "mass_update": false,
            "multiselectlookup": {},
            "pick_list_values": [],
            "auto_number": {}
        },
        {
            "system_mandatory": false,
            "webhook": true,
            "json_type": "string",
            "crypt": null,
            "field_label": "Quote Stage",
            "tooltip": null,
            "created_source": "default",
            "field_read_only": false,
            "display_label": "Quote Stage",
            "ui_type": 2,
            "read_only": false,
            "association_details": null,
            "quick_sequence_number": "2",
            "businesscard_supported": true,
            "currency": {},
            "id": "5653678000000002873",
            "custom_field": false,
            "lookup": {},
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 120,
            "view_type": {
                "view": true,
                "edit": true,
                "quick_create": true,
                "create": true
            },
            "subform": null,
            "external": null,
            "api_name": "Quote_Stage",
            "unique": {},
            "history_tracking": false,
            "data_type": "picklist",
            "formula": {},
            "decimal_place": null,
            "mass_update": true,
            "blueprint_supported": true,
            "multiselectlookup": {},
            "pick_list_values": [
                {
                    "display_value": "Draft",
                    "reference_value": "Draft",
                    "actual_value": "Draft"
                },
                {
                    "display_value": "Negotiation",
                    "reference_value": "Negotiation",
                    "actual_value": "Negotiation"
                },
                {
                    "display_value": "Delivered",
                    "reference_value": "Delivered",
                    "actual_value": "Delivered"
                },
                {
                    "display_value": "On Hold",
                    "reference_value": "On Hold",
                    "actual_value": "On Hold"
                },
                {
                    "display_value": "Confirmed",
                    "reference_value": "Confirmed",
                    "actual_value": "Confirmed"
                },
                {
                    "display_value": "Closed Won",
                    "reference_value": "Closed Won",
                    "actual_value": "Closed Won"
                },
                {
                    "display_value": "Closed Lost",
                    "reference_value": "Closed Lost",
                    "actual_value": "Closed Lost"
                }
            ],
            "auto_number": {}
        },
        {
            "system_mandatory": false,
            "webhook": true,
            "json_type": "string",
            "crypt": null,
            "field_label": "Specification",
            "tooltip": null,
            "textarea": {
                "type": "small"
            },
            "created_source": "default",
            "field_read_only": false,
            "display_label": "Specification",
            "ui_type": 110,
            "read_only": false,
            "association_details": null,
            "businesscard_supported": true,
            "currency": {},
            "id": "5653678000000810954",
            "custom_field": true,
            "lookup": {},
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 2000,
            "view_type": {
                "view": true,
                "edit": true,
                "quick_create": false,
                "create": true
            },
            "subform": null,
            "external": null,
            "api_name": "Specification",
            "unique": {},
            "history_tracking": false,
            "data_type": "textarea",
            "formula": {},
            "decimal_place": null,
            "mass_update": false,
            "multiselectlookup": {},
            "pick_list_values": [],
            "auto_number": {}
        },
        {
            "system_mandatory": false,
            "webhook": true,
            "json_type": "string",
            "crypt": null,
            "field_label": "Team",
            "tooltip": null,
            "created_source": "default",
            "field_read_only": false,
            "display_label": "Team",
            "ui_type": 1,
            "read_only": false,
            "association_details": null,
            "businesscard_supported": true,
            "currency": {},
            "id": "5653678000000002877",
            "custom_field": false,
            "lookup": {},
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 120,
            "view_type": {
                "view": true,
                "edit": true,
                "quick_create": false,
                "create": true
            },
            "subform": null,
            "external": null,
            "api_name": "Team",
            "unique": {},
            "history_tracking": false,
            "data_type": "text",
            "formula": {},
            "decimal_place": null,
            "mass_update": true,
            "multiselectlookup": {},
            "pick_list_values": [],
            "auto_number": {}
        },
        {
            "system_mandatory": false,
            "webhook": true,
            "json_type": "string",
            "crypt": null,
            "field_label": "General Exclusion.",
            "tooltip": null,
            "textarea": {
                "type": "large"
            },
            "created_source": "default",
            "field_read_only": false,
            "display_label": "General Exclusion.",
            "ui_type": 3,
            "read_only": false,
            "association_details": null,
            "businesscard_supported": true,
            "currency": {},
            "id": "5653678000001141016",
            "custom_field": true,
            "lookup": {},
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 32000,
            "view_type": {
                "view": true,
                "edit": true,
                "quick_create": false,
                "create": true
            },
            "subform": null,
            "external": null,
            "api_name": "General_Exclusion",
            "unique": {},
            "history_tracking": false,
            "data_type": "textarea",
            "formula": {},
            "decimal_place": null,
            "mass_update": false,
            "multiselectlookup": {},
            "pick_list_values": [],
            "auto_number": {}
        },
        {
            "system_mandatory": false,
            "webhook": true,
            "json_type": "string",
            "crypt": null,
            "field_label": "Carrier",
            "tooltip": null,
            "created_source": "default",
            "field_read_only": false,
            "display_label": "Carrier",
            "ui_type": 2,
            "read_only": false,
            "association_details": null,
            "businesscard_supported": true,
            "currency": {},
            "id": "5653678000000002881",
            "custom_field": false,
            "lookup": {},
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 120,
            "view_type": {
                "view": true,
                "edit": true,
                "quick_create": false,
                "create": true
            },
            "subform": null,
            "external": null,
            "api_name": "Carrier",
            "unique": {},
            "history_tracking": false,
            "data_type": "picklist",
            "formula": {},
            "decimal_place": null,
            "mass_update": true,
            "blueprint_supported": false,
            "multiselectlookup": {},
            "pick_list_values": [
                {
                    "display_value": "FedEX",
                    "reference_value": "FedEX",
                    "actual_value": "FedEX"
                },
                {
                    "display_value": "UPS",
                    "reference_value": "UPS",
                    "actual_value": "UPS"
                },
                {
                    "display_value": "USPS",
                    "reference_value": "USPS",
                    "actual_value": "USPS"
                },
                {
                    "display_value": "DHL",
                    "reference_value": "DHL",
                    "actual_value": "DHL"
                },
                {
                    "display_value": "BlueDart",
                    "reference_value": "BlueDart",
                    "actual_value": "BlueDart"
                }
            ],
            "auto_number": {}
        },
        {
            "system_mandatory": false,
            "webhook": true,
            "json_type": "string",
            "crypt": null,
            "field_label": "Modified Time",
            "tooltip": null,
            "created_source": "default",
            "field_read_only": false,
            "display_label": "Modified Time",
            "ui_type": 200,
            "read_only": false,
            "association_details": null,
            "businesscard_supported": false,
            "currency": {},
            "id": "5653678000000002893",
            "custom_field": false,
            "lookup": {},
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 120,
            "view_type": {
                "view": true,
                "edit": false,
                "quick_create": false,
                "create": false
            },
            "subform": null,
            "external": null,
            "api_name": "Modified_Time",
            "unique": {},
            "history_tracking": false,
            "data_type": "datetime",
            "formula": {},
            "decimal_place": null,
            "mass_update": false,
            "multiselectlookup": {},
            "pick_list_values": [],
            "auto_number": {}
        },
        {
            "system_mandatory": false,
            "webhook": true,
            "json_type": "jsonobject",
            "crypt": null,
            "field_label": "Created By",
            "tooltip": null,
            "created_source": "default",
            "field_read_only": false,
            "display_label": "Created By",
            "ui_type": 20,
            "read_only": false,
            "association_details": null,
            "businesscard_supported": true,
            "currency": {},
            "id": "5653678000000002887",
            "custom_field": false,
            "lookup": {},
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 120,
            "view_type": {
                "view": true,
                "edit": false,
                "quick_create": false,
                "create": false
            },
            "subform": null,
            "external": null,
            "api_name": "Created_By",
            "unique": {},
            "history_tracking": false,
            "data_type": "ownerlookup",
            "formula": {},
            "decimal_place": null,
            "mass_update": false,
            "multiselectlookup": {},
            "pick_list_values": [],
            "auto_number": {}
        },
        {
            "system_mandatory": false,
            "webhook": true,
            "json_type": "string",
            "crypt": null,
            "field_label": "Brand",
            "tooltip": null,
            "created_source": "default",
            "field_read_only": false,
            "display_label": "Brand",
            "ui_type": 1,
            "read_only": false,
            "association_details": null,
            "businesscard_supported": true,
            "currency": {},
            "id": "5653678000001141239",
            "custom_field": true,
            "lookup": {},
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 255,
            "view_type": {
                "view": true,
                "edit": true,
                "quick_create": false,
                "create": true
            },
            "subform": null,
            "external": null,
            "api_name": "Brand",
            "unique": {},
            "history_tracking": false,
            "data_type": "text",
            "formula": {},
            "decimal_place": null,
            "mass_update": true,
            "multiselectlookup": {},
            "pick_list_values": [],
            "auto_number": {}
        },
        {
            "system_mandatory": false,
            "webhook": true,
            "json_type": "string",
            "crypt": null,
            "field_label": "Currency",
            "tooltip": null,
            "created_source": "default",
            "field_read_only": false,
            "display_label": "Currency",
            "ui_type": 39,
            "read_only": false,
            "association_details": null,
            "businesscard_supported": true,
            "currency": {},
            "id": "5653678000000050047",
            "custom_field": false,
            "lookup": {},
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 120,
            "view_type": {
                "view": true,
                "edit": true,
                "quick_create": false,
                "create": true
            },
            "subform": null,
            "external": null,
            "api_name": "Currency",
            "unique": {},
            "history_tracking": false,
            "data_type": "picklist",
            "formula": {},
            "decimal_place": null,
            "mass_update": false,
            "blueprint_supported": false,
            "multiselectlookup": {},
            "pick_list_values": [
                {
                    "display_value": "AED",
                    "reference_value": "AED",
                    "actual_value": "AED"
                }
            ],
            "auto_number": {}
        },
        {
            "system_mandatory": false,
            "webhook": true,
            "json_type": "jsonarray",
            "crypt": null,
            "field_label": "Tag",
            "tooltip": null,
            "created_source": "default",
            "field_read_only": false,
            "display_label": "Tag",
            "ui_type": 209,
            "read_only": false,
            "association_details": null,
            "businesscard_supported": false,
            "currency": {},
            "id": "5653678000000125037",
            "custom_field": false,
            "lookup": {},
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 2000,
            "view_type": {
                "view": true,
                "edit": false,
                "quick_create": false,
                "create": false
            },
            "subform": null,
            "external": null,
            "api_name": "Tag",
            "unique": {},
            "history_tracking": false,
            "data_type": "text",
            "formula": {},
            "decimal_place": null,
            "mass_update": false,
            "multiselectlookup": {},
            "pick_list_values": [],
            "auto_number": {}
        },
        {
            "system_mandatory": false,
            "webhook": true,
            "json_type": "string",
            "crypt": null,
            "field_label": "Created Time",
            "tooltip": null,
            "created_source": "default",
            "field_read_only": false,
            "display_label": "Created Time",
            "ui_type": 200,
            "read_only": false,
            "association_details": null,
            "businesscard_supported": false,
            "currency": {},
            "id": "5653678000000002891",
            "custom_field": false,
            "lookup": {},
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 120,
            "view_type": {
                "view": true,
                "edit": false,
                "quick_create": false,
                "create": false
            },
            "subform": null,
            "external": null,
            "api_name": "Created_Time",
            "unique": {},
            "history_tracking": false,
            "data_type": "datetime",
            "formula": {},
            "decimal_place": null,
            "mass_update": false,
            "multiselectlookup": {},
            "pick_list_values": [],
            "auto_number": {}
        },
        {
            "system_mandatory": false,
            "webhook": true,
            "json_type": "string",
            "crypt": null,
            "field_label": "Warranty",
            "tooltip": null,
            "created_source": "default",
            "field_read_only": false,
            "display_label": "Warranty",
            "ui_type": 1,
            "read_only": false,
            "association_details": null,
            "businesscard_supported": true,
            "currency": {},
            "id": "5653678000001141246",
            "custom_field": true,
            "lookup": {},
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 255,
            "view_type": {
                "view": true,
                "edit": true,
                "quick_create": false,
                "create": true
            },
            "subform": null,
            "external": null,
            "api_name": "Warranty",
            "unique": {},
            "history_tracking": false,
            "data_type": "text",
            "formula": {},
            "decimal_place": null,
            "mass_update": true,
            "multiselectlookup": {},
            "pick_list_values": [],
            "auto_number": {}
        },
        {
            "system_mandatory": false,
            "webhook": true,
            "json_type": "string",
            "crypt": null,
            "field_label": "Delivery",
            "tooltip": null,
            "created_source": "default",
            "field_read_only": false,
            "display_label": "Delivery",
            "ui_type": 1,
            "read_only": false,
            "association_details": null,
            "businesscard_supported": true,
            "currency": {},
            "id": "5653678000001141253",
            "custom_field": true,
            "lookup": {},
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 255,
            "view_type": {
                "view": true,
                "edit": true,
                "quick_create": false,
                "create": true
            },
            "subform": null,
            "external": null,
            "api_name": "Delivery",
            "unique": {},
            "history_tracking": false,
            "data_type": "text",
            "formula": {},
            "decimal_place": null,
            "mass_update": true,
            "multiselectlookup": {},
            "pick_list_values": [],
            "auto_number": {}
        },
        {
            "system_mandatory": false,
            "webhook": false,
            "json_type": "boolean",
            "crypt": null,
            "field_label": "Locked",
            "tooltip": null,
            "created_source": "default",
            "field_read_only": true,
            "display_label": "Locked",
            "ui_type": 301,
            "read_only": true,
            "association_details": null,
            "businesscard_supported": false,
            "currency": {},
            "id": "5653678000000375038",
            "custom_field": false,
            "lookup": {},
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 5,
            "view_type": {
                "view": false,
                "edit": false,
                "quick_create": false,
                "create": false
            },
            "subform": null,
            "external": null,
            "api_name": "Locked__s",
            "unique": {},
            "history_tracking": false,
            "data_type": "boolean",
            "formula": {},
            "decimal_place": null,
            "mass_update": false,
            "multiselectlookup": {},
            "pick_list_values": [],
            "auto_number": {}
        },
        {
            "system_mandatory": false,
            "webhook": true,
            "json_type": "string",
            "crypt": null,
            "field_label": "Billing Street",
            "tooltip": null,
            "created_source": "default",
            "field_read_only": false,
            "display_label": "Billing Street",
            "ui_type": 1,
            "read_only": false,
            "association_details": null,
            "businesscard_supported": true,
            "currency": {},
            "id": "5653678000000002905",
            "custom_field": false,
            "lookup": {},
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 250,
            "view_type": {
                "view": true,
                "edit": true,
                "quick_create": false,
                "create": true
            },
            "subform": null,
            "external": null,
            "api_name": "Billing_Street",
            "unique": {},
            "history_tracking": false,
            "data_type": "text",
            "formula": {},
            "decimal_place": null,
            "mass_update": true,
            "multiselectlookup": {},
            "pick_list_values": [],
            "auto_number": {}
        },
        {
            "system_mandatory": false,
            "webhook": true,
            "json_type": "string",
            "crypt": null,
            "field_label": "Shipping Street",
            "tooltip": null,
            "created_source": "default",
            "field_read_only": false,
            "display_label": "Shipping Street",
            "ui_type": 1,
            "read_only": false,
            "association_details": null,
            "businesscard_supported": true,
            "currency": {},
            "id": "5653678000000002907",
            "custom_field": false,
            "lookup": {},
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 250,
            "view_type": {
                "view": true,
                "edit": true,
                "quick_create": false,
                "create": true
            },
            "subform": null,
            "external": null,
            "api_name": "Shipping_Street",
            "unique": {},
            "history_tracking": false,
            "data_type": "text",
            "formula": {},
            "decimal_place": null,
            "mass_update": true,
            "multiselectlookup": {},
            "pick_list_values": [],
            "auto_number": {}
        },
        {
            "system_mandatory": false,
            "webhook": true,
            "json_type": "string",
            "crypt": null,
            "field_label": "Billing City",
            "tooltip": null,
            "created_source": "default",
            "field_read_only": false,
            "display_label": "Billing City",
            "ui_type": 1,
            "read_only": false,
            "association_details": null,
            "businesscard_supported": true,
            "currency": {},
            "id": "5653678000000002909",
            "custom_field": false,
            "lookup": {},
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 100,
            "view_type": {
                "view": true,
                "edit": true,
                "quick_create": false,
                "create": true
            },
            "subform": null,
            "external": null,
            "api_name": "Billing_City",
            "unique": {},
            "history_tracking": false,
            "data_type": "text",
            "formula": {},
            "decimal_place": null,
            "mass_update": true,
            "multiselectlookup": {},
            "pick_list_values": [],
            "auto_number": {}
        },
        {
            "system_mandatory": false,
            "webhook": true,
            "json_type": "string",
            "crypt": null,
            "field_label": "Shipping City",
            "tooltip": null,
            "created_source": "default",
            "field_read_only": false,
            "display_label": "Shipping City",
            "ui_type": 1,
            "read_only": false,
            "association_details": null,
            "businesscard_supported": true,
            "currency": {},
            "id": "5653678000000002911",
            "custom_field": false,
            "lookup": {},
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 100,
            "view_type": {
                "view": true,
                "edit": true,
                "quick_create": false,
                "create": true
            },
            "subform": null,
            "external": null,
            "api_name": "Shipping_City",
            "unique": {},
            "history_tracking": false,
            "data_type": "text",
            "formula": {},
            "decimal_place": null,
            "mass_update": true,
            "multiselectlookup": {},
            "pick_list_values": [],
            "auto_number": {}
        },
        {
            "system_mandatory": false,
            "webhook": true,
            "json_type": "string",
            "crypt": null,
            "field_label": "Billing State",
            "tooltip": null,
            "created_source": "default",
            "field_read_only": false,
            "display_label": "Billing State",
            "ui_type": 1,
            "read_only": false,
            "association_details": null,
            "businesscard_supported": true,
            "currency": {},
            "id": "5653678000000002913",
            "custom_field": false,
            "lookup": {},
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 100,
            "view_type": {
                "view": true,
                "edit": true,
                "quick_create": false,
                "create": true
            },
            "subform": null,
            "external": null,
            "api_name": "Billing_State",
            "unique": {},
            "history_tracking": false,
            "data_type": "text",
            "formula": {},
            "decimal_place": null,
            "mass_update": true,
            "multiselectlookup": {},
            "pick_list_values": [],
            "auto_number": {}
        },
        {
            "system_mandatory": false,
            "webhook": true,
            "json_type": "string",
            "crypt": null,
            "field_label": "Shipping State",
            "tooltip": null,
            "created_source": "default",
            "field_read_only": false,
            "display_label": "Shipping State",
            "ui_type": 1,
            "read_only": false,
            "association_details": null,
            "businesscard_supported": true,
            "currency": {},
            "id": "5653678000000002915",
            "custom_field": false,
            "lookup": {},
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 100,
            "view_type": {
                "view": true,
                "edit": true,
                "quick_create": false,
                "create": true
            },
            "subform": null,
            "external": null,
            "api_name": "Shipping_State",
            "unique": {},
            "history_tracking": false,
            "data_type": "text",
            "formula": {},
            "decimal_place": null,
            "mass_update": true,
            "multiselectlookup": {},
            "pick_list_values": [],
            "auto_number": {}
        },
        {
            "system_mandatory": false,
            "webhook": true,
            "json_type": "string",
            "crypt": null,
            "field_label": "Billing Code",
            "tooltip": null,
            "created_source": "default",
            "field_read_only": false,
            "display_label": "Billing Code",
            "ui_type": 1,
            "read_only": false,
            "association_details": null,
            "businesscard_supported": true,
            "currency": {},
            "id": "5653678000000002917",
            "custom_field": false,
            "lookup": {},
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 30,
            "view_type": {
                "view": true,
                "edit": true,
                "quick_create": false,
                "create": true
            },
            "subform": null,
            "external": null,
            "api_name": "Billing_Code",
            "unique": {},
            "history_tracking": false,
            "data_type": "text",
            "formula": {},
            "decimal_place": null,
            "mass_update": true,
            "multiselectlookup": {},
            "pick_list_values": [],
            "auto_number": {}
        },
        {
            "system_mandatory": false,
            "webhook": true,
            "json_type": "string",
            "crypt": null,
            "field_label": "Shipping Code",
            "tooltip": null,
            "created_source": "default",
            "field_read_only": false,
            "display_label": "Shipping Code",
            "ui_type": 1,
            "read_only": false,
            "association_details": null,
            "businesscard_supported": true,
            "currency": {},
            "id": "5653678000000002919",
            "custom_field": false,
            "lookup": {},
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 30,
            "view_type": {
                "view": true,
                "edit": true,
                "quick_create": false,
                "create": true
            },
            "subform": null,
            "external": null,
            "api_name": "Shipping_Code",
            "unique": {},
            "history_tracking": false,
            "data_type": "text",
            "formula": {},
            "decimal_place": null,
            "mass_update": true,
            "multiselectlookup": {},
            "pick_list_values": [],
            "auto_number": {}
        },
        {
            "system_mandatory": false,
            "webhook": true,
            "json_type": "string",
            "crypt": null,
            "field_label": "Billing Country",
            "tooltip": null,
            "created_source": "default",
            "field_read_only": false,
            "display_label": "Billing Country",
            "ui_type": 1,
            "read_only": false,
            "association_details": null,
            "businesscard_supported": true,
            "currency": {},
            "id": "5653678000000002921",
            "custom_field": false,
            "lookup": {},
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 100,
            "view_type": {
                "view": true,
                "edit": true,
                "quick_create": false,
                "create": true
            },
            "subform": null,
            "external": null,
            "api_name": "Billing_Country",
            "unique": {},
            "history_tracking": false,
            "data_type": "text",
            "formula": {},
            "decimal_place": null,
            "mass_update": true,
            "multiselectlookup": {},
            "pick_list_values": [],
            "auto_number": {}
        },
        {
            "system_mandatory": false,
            "webhook": true,
            "json_type": "string",
            "crypt": null,
            "field_label": "Shipping Country",
            "tooltip": null,
            "created_source": "default",
            "field_read_only": false,
            "display_label": "Shipping Country",
            "ui_type": 1,
            "read_only": false,
            "association_details": null,
            "businesscard_supported": true,
            "currency": {},
            "id": "5653678000000002923",
            "custom_field": false,
            "lookup": {},
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 100,
            "view_type": {
                "view": true,
                "edit": true,
                "quick_create": false,
                "create": true
            },
            "subform": null,
            "external": null,
            "api_name": "Shipping_Country",
            "unique": {},
            "history_tracking": false,
            "data_type": "text",
            "formula": {},
            "decimal_place": null,
            "mass_update": true,
            "multiselectlookup": {},
            "pick_list_values": [],
            "auto_number": {}
        },
        {
            "system_mandatory": true,
            "webhook": true,
            "json_type": "jsonarray",
            "crypt": null,
            "field_label": "Product Details",
            "tooltip": null,
            "created_source": "default",
            "field_read_only": false,
            "display_label": "Product Details",
            "ui_type": 50,
            "read_only": false,
            "association_details": null,
            "quick_sequence_number": "4",
            "businesscard_supported": true,
            "currency": {},
            "id": "5653678000000002925",
            "custom_field": false,
            "lookup": {},
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 1000,
            "view_type": {
                "view": true,
                "edit": true,
                "quick_create": true,
                "create": true
            },
            "subform": null,
            "external": null,
            "api_name": "Product_Details",
            "unique": {},
            "history_tracking": false,
            "data_type": "text",
            "formula": {},
            "decimal_place": null,
            "mass_update": false,
            "multiselectlookup": {},
            "pick_list_values": [],
            "auto_number": {}
        },
        {
            "system_mandatory": false,
            "webhook": true,
            "json_type": "string",
            "crypt": null,
            "field_label": "Terms and Conditions",
            "tooltip": null,
            "textarea": {
                "type": "large"
            },
            "created_source": "default",
            "field_read_only": false,
            "display_label": "Terms and Conditions",
            "ui_type": 3,
            "read_only": false,
            "association_details": null,
            "businesscard_supported": true,
            "currency": {},
            "id": "5653678000000002927",
            "custom_field": false,
            "lookup": {},
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 32000,
            "view_type": {
                "view": true,
                "edit": true,
                "quick_create": false,
                "create": true
            },
            "subform": null,
            "external": null,
            "api_name": "Terms_and_Conditions",
            "unique": {},
            "history_tracking": false,
            "data_type": "textarea",
            "formula": {},
            "decimal_place": null,
            "mass_update": false,
            "multiselectlookup": {},
            "pick_list_values": [],
            "auto_number": {}
        },
        {
            "system_mandatory": false,
            "webhook": true,
            "json_type": "string",
            "crypt": null,
            "field_label": "Description",
            "tooltip": null,
            "textarea": {
                "type": "large"
            },
            "created_source": "default",
            "field_read_only": false,
            "display_label": "Description",
            "ui_type": 3,
            "read_only": false,
            "association_details": null,
            "businesscard_supported": true,
            "currency": {},
            "id": "5653678000000002929",
            "custom_field": false,
            "lookup": {},
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 32000,
            "view_type": {
                "view": true,
                "edit": true,
                "quick_create": false,
                "create": true
            },
            "subform": null,
            "external": null,
            "api_name": "Description",
            "unique": {},
            "history_tracking": false,
            "data_type": "textarea",
            "formula": {},
            "decimal_place": null,
            "mass_update": false,
            "multiselectlookup": {},
            "pick_list_values": [],
            "auto_number": {}
        },
        {
            "system_mandatory": false,
            "webhook": true,
            "json_type": "double",
            "crypt": null,
            "field_label": "Sub Total",
            "tooltip": null,
            "created_source": "default",
            "field_read_only": false,
            "display_label": "Sub Total",
            "ui_type": 77,
            "read_only": true,
            "association_details": null,
            "businesscard_supported": true,
            "currency": {
                "rounding_option": "round_off",
                "precision": 2
            },
            "id": "5653678000000002895",
            "custom_field": false,
            "lookup": {},
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 16,
            "view_type": {
                "view": true,
                "edit": true,
                "quick_create": false,
                "create": true
            },
            "subform": null,
            "external": null,
            "api_name": "Sub_Total",
            "unique": {},
            "history_tracking": false,
            "data_type": "currency",
            "formula": {},
            "query_details": null,
            "decimal_place": 9,
            "mass_update": false,
            "multiselectlookup": {},
            "pick_list_values": [],
            "auto_number": {}
        },
        {
            "system_mandatory": false,
            "webhook": true,
            "json_type": "double",
            "crypt": null,
            "field_label": "Discount",
            "tooltip": null,
            "created_source": "default",
            "field_read_only": false,
            "display_label": "Discount",
            "ui_type": 77,
            "read_only": false,
            "association_details": null,
            "businesscard_supported": true,
            "currency": {
                "rounding_option": "round_off",
                "precision": 2
            },
            "id": "5653678000000024001",
            "custom_field": false,
            "lookup": {},
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 16,
            "view_type": {
                "view": true,
                "edit": true,
                "quick_create": false,
                "create": true
            },
            "subform": null,
            "external": null,
            "api_name": "Discount",
            "unique": {},
            "history_tracking": false,
            "data_type": "currency",
            "formula": {},
            "decimal_place": 9,
            "mass_update": false,
            "multiselectlookup": {},
            "pick_list_values": [],
            "auto_number": {}
        },
        {
            "system_mandatory": false,
            "webhook": true,
            "json_type": "double",
            "crypt": null,
            "field_label": "VAT",
            "tooltip": null,
            "created_source": "default",
            "field_read_only": false,
            "display_label": "Tax",
            "ui_type": 77,
            "read_only": true,
            "association_details": null,
            "businesscard_supported": true,
            "currency": {
                "rounding_option": "round_off",
                "precision": 2
            },
            "id": "5653678000000002897",
            "custom_field": false,
            "lookup": {},
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 16,
            "view_type": {
                "view": true,
                "edit": true,
                "quick_create": false,
                "create": true
            },
            "subform": null,
            "external": null,
            "api_name": "Tax",
            "unique": {},
            "history_tracking": false,
            "data_type": "currency",
            "formula": {},
            "decimal_place": 9,
            "mass_update": false,
            "multiselectlookup": {},
            "pick_list_values": [],
            "auto_number": {}
        },
        {
            "system_mandatory": false,
            "webhook": true,
            "json_type": "double",
            "crypt": null,
            "field_label": "Adjustment",
            "tooltip": null,
            "created_source": "default",
            "field_read_only": false,
            "display_label": "Adjustment",
            "ui_type": 77,
            "read_only": false,
            "association_details": null,
            "businesscard_supported": true,
            "currency": {
                "rounding_option": "round_off",
                "precision": 2
            },
            "id": "5653678000000002899",
            "custom_field": false,
            "lookup": {},
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 16,
            "view_type": {
                "view": true,
                "edit": true,
                "quick_create": false,
                "create": true
            },
            "subform": null,
            "external": null,
            "api_name": "Adjustment",
            "unique": {},
            "history_tracking": false,
            "data_type": "currency",
            "formula": {},
            "decimal_place": 9,
            "mass_update": false,
            "multiselectlookup": {},
            "pick_list_values": [],
            "auto_number": {}
        },
        {
            "system_mandatory": false,
            "webhook": true,
            "json_type": "double",
            "crypt": null,
            "field_label": "Grand Total",
            "tooltip": null,
            "created_source": "default",
            "field_read_only": false,
            "display_label": "Grand Total",
            "ui_type": 77,
            "read_only": true,
            "association_details": null,
            "businesscard_supported": true,
            "currency": {
                "rounding_option": "round_off",
                "precision": 2
            },
            "id": "5653678000000002901",
            "custom_field": false,
            "lookup": {},
            "convert_mapping": {
                "Invoices": null,
                "Sales_Orders": null
            },
            "visible": true,
            "length": 16,
            "view_type": {
                "view": true,
                "edit": true,
                "quick_create": false,
                "create": true
            },
            "subform": null,
            "external": null,
            "api_name": "Grand_Total",
            "unique": {},
            "history_tracking": false,
            "data_type": "currency",
            "formula": {},
            "decimal_place": 9,
            "mass_update": false,
            "multiselectlookup": {},
            "pick_list_values": [],
            "auto_number": {}
        }
    ]
}
